import type { AuditEntry } from "./types";

export const seedAudits: AuditEntry[] = [
  {
    id: "a-001",
    sectionId: "PSW/02",
    buildingCode: "PSW",
    timestamp: "2026-05-19T09:12:00Z",
    auditor: "M. Hargreaves",
    ragBefore: "amber",
    ragAfter: "red",
    lifeRemainingYears: 2,
    notes: "Severe ponding around AHU base, felt blistering across 60% of section. Membrane life effectively exhausted.",
    area: "Main covering",
  },
  {
    id: "a-002",
    sectionId: "CHC/03",
    buildingCode: "CHC",
    timestamp: "2026-05-17T13:45:00Z",
    auditor: "R. Patel",
    ragBefore: "amber",
    ragAfter: "red",
    lifeRemainingYears: 3,
    notes: "Two active leaks reported by occupants. Flashings around rooflights detached. Recommend full strip and replace within FY.",
    area: "Flashings",
  },
  {
    id: "a-003",
    sectionId: "HOD/07",
    buildingCode: "HOD",
    timestamp: "2026-05-14T10:30:00Z",
    auditor: "M. Hargreaves",
    ragBefore: "green",
    ragAfter: "amber",
    lifeRemainingYears: 8,
    notes: "Surface scuffing and minor splits at lap joints. Patch repair scheduled. Monitor at next 12-month inspection.",
    area: "Main covering",
  },
  {
    id: "a-004",
    sectionId: "RIL/01",
    buildingCode: "RIL",
    timestamp: "2026-05-08T15:20:00Z",
    auditor: "S. Chen",
    ragBefore: "red",
    ragAfter: "red",
    lifeRemainingYears: 3,
    notes: "Re-inspected following remedial scope. Confirmed status — capital replacement required in 26/27 budget cycle.",
    area: "Drainage outlets",
  },
  {
    id: "a-005",
    sectionId: "SCE/04",
    buildingCode: "SCE",
    timestamp: "2026-04-28T11:05:00Z",
    auditor: "R. Patel",
    ragBefore: "amber",
    ragAfter: "amber",
    lifeRemainingYears: 11,
    notes: "Inspection following gutter clean. Outlets clear, no new defects. Status holds.",
    area: "Gutters",
  },
  {
    id: "a-006",
    sectionId: "JBP/02",
    buildingCode: "JBP",
    timestamp: "2026-04-22T14:00:00Z",
    auditor: "S. Chen",
    ragBefore: "green",
    ragAfter: "green",
    lifeRemainingYears: 23,
    notes: "Annual standing-seam inspection. Fixings tight, no thermal expansion damage. Excellent condition for age.",
    area: "Main covering",
  },
  {
    id: "a-007",
    sectionId: "ATR/01",
    buildingCode: "ATR",
    timestamp: "2026-04-15T09:45:00Z",
    auditor: "M. Hargreaves",
    ragBefore: "amber",
    ragAfter: "amber",
    lifeRemainingYears: 9,
    notes: "Sealant degradation around perimeter detected. Reseal works programmed for summer recess.",
    area: "Skylights / rooflights",
  },
  {
    id: "a-008",
    sectionId: "GRH/01",
    buildingCode: "GRH",
    timestamp: "2026-04-09T16:10:00Z",
    auditor: "R. Patel",
    ragBefore: "amber",
    ragAfter: "red",
    lifeRemainingYears: 3,
    notes: "Slate displacement following storm. Multiple slipped tiles, water ingress in adjacent corridor. Urgent works raised.",
    area: "Main covering",
  },
];
